kind: Deployment
apiVersion: apps/v1
metadata:
  name: bitcoin-price-events
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-price-events
  template:
    metadata:
      labels:
        app: bitcoin-price-events
    spec:
      containers:
        - name: bitcoin-price-events
          image: stuartloxton/bitcoin-price-events:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: BTC_EVENT_TOPIC
              value: "adapter.bitcoin-price.raw.v1"
            - name: AVG_PRICE_TOPIC
              value: "aggregated.avg-bitcoin-price.v1"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schemaregistry:8081"
            - name: STREAMS_BTC_GROUPID
              value: "consumer-stock-bitcoin-price.v1"
            - name: CONSUMER_BTC_GROUPID
              value: "consumer-avg-bitcoin-price.v1.2"
            - name: HAS_SECRET
              value: "true"
