kind: Deployment
apiVersion: apps/v1
metadata:
  name: bitcoin-price-adapter
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-price-adapter
  template:
    metadata:
      labels:
        app: bitcoin-price-adapter
    spec:
      containers:
        - name: bitcoin-price-adapter
          image: stuartloxton/bitcoin-price-adapter:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name:  BTC_EVENT_TOPIC
              value: "adapter.test-bitcoin.v1"
            - name:  KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schemaregistry:8081"
