spring:
  main:
    allow-bean-definition-overriding: true

application:
  btc-stream-uri: ${BTC_STREAM_URI}
  kafka:
    btc-event-topic: ${BTC_EVENT_TOPIC}
    avg-price-topic: ${AVG_PRICE_TOPIC}
    bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry: ${SCHEMA_REGISTRY_URL}
    group-id: ${STREAMS_BTC_GROUPID}
