spring:
  main:
    allow-bean-definition-overriding: true

application:
  kafka:
    btc-event-topic: ${BTC_EVENT_TOPIC}
    btc-metrics-topic: ${BTC_METRICS_TOPIC}
    bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry: ${SCHEMA_REGISTRY_URL}
    group-id: ${STREAMS_BTC_GROUPID}
    avg-btc-group-id: ${CONSUMER_BTC_GROUPID}
    hasSecret: ${HAS_SECRET}
    username: "test"
    password: "test123"