spring:
  main:
    allow-bean-definition-overriding: true

application:
  binance-uri: ${BINANCE_URI:wss://stream.binance.com/stream?streams=!miniTicker@arr@3000ms/btcusdt@depth.b10/btcusdt@aggTrade.b10}
  kafka:
    bootstrap: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    schema-registry: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    crypto-price-topic: ${CRYPTO_PRICE_TOPIC:crypto.binance.quote.v1}
    hasSecret: false
    username: test
    password: test123