spring:
  main:
    allow-bean-definition-overriding: true

application:
  btc-stream-url: ${BTC_STREAM_URL}
  kafka:
    bootstrap: ${BOOTSTRAP_SERVER}
    btc-event-topic: ${BTC_EVENT_TOPIC}
    hasSecret: true
    username: ${KAFKA_USERNAME}
    password: ${KAFKA_PASSWORD}
  schema-registry:
    url: ${SCHEMA_REGISTRY_URL}
    username: ${SR_USERNAME}
    password: ${SR_PASSWORD}