spring:
  main:
    allow-bean-definition-overriding: true

application:
  btc-stream-uri: ${BTC_STREAM_URI}
  kafka:
    bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry: ${SCHEMA_REGISTRY_URL}
    btc-event-topic: ${BTC_EVENT_TOPIC}
    hasSecret: false
    username: "test"
    password: "test123"